# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nkn-config-map
# data:
#   config.json: |
#       {
#         "BeneficiaryAddr": "",
#         "SeedList": [
#           "http://mainnet-seed-0001.nkn.org:30003",
#           "http://mainnet-seed-0002.nkn.org:30003",
#           "http://mainnet-seed-0003.nkn.org:30003",
#           "http://mainnet-seed-0004.nkn.org:30003",
#           "http://mainnet-seed-0005.nkn.org:30003",
#           "http://mainnet-seed-0006.nkn.org:30003",
#           "http://mainnet-seed-0007.nkn.org:30003",
#           "http://mainnet-seed-0008.nkn.org:30003",
#           "http://mainnet-seed-0009.nkn.org:30003",
#           "http://mainnet-seed-0010.nkn.org:30003",
#           "http://mainnet-seed-0011.nkn.org:30003",
#           "http://mainnet-seed-0012.nkn.org:30003",
#           "http://mainnet-seed-0013.nkn.org:30003",
#           "http://mainnet-seed-0014.nkn.org:30003",
#           "http://mainnet-seed-0015.nkn.org:30003",
#           "http://mainnet-seed-0016.nkn.org:30003",
#           "http://mainnet-seed-0017.nkn.org:30003",
#           "http://mainnet-seed-0018.nkn.org:30003",
#           "http://mainnet-seed-0019.nkn.org:30003",
#           "http://mainnet-seed-0020.nkn.org:30003",
#           "http://mainnet-seed-0021.nkn.org:30003",
#           "http://mainnet-seed-0022.nkn.org:30003",
#           "http://mainnet-seed-0023.nkn.org:30003",
#           "http://mainnet-seed-0024.nkn.org:30003",
#           "http://mainnet-seed-0025.nkn.org:30003",
#           "http://mainnet-seed-0026.nkn.org:30003",
#           "http://mainnet-seed-0027.nkn.org:30003",
#           "http://mainnet-seed-0028.nkn.org:30003",
#           "http://mainnet-seed-0029.nkn.org:30003",
#           "http://mainnet-seed-0030.nkn.org:30003",
#           "http://mainnet-seed-0031.nkn.org:30003",
#           "http://mainnet-seed-0032.nkn.org:30003",
#           "http://mainnet-seed-0033.nkn.org:30003",
#           "http://mainnet-seed-0034.nkn.org:30003",
#           "http://mainnet-seed-0035.nkn.org:30003",
#           "http://mainnet-seed-0036.nkn.org:30003",
#           "http://mainnet-seed-0037.nkn.org:30003",
#           "http://mainnet-seed-0038.nkn.org:30003",
#           "http://mainnet-seed-0039.nkn.org:30003",
#           "http://mainnet-seed-0040.nkn.org:30003",
#           "http://mainnet-seed-0041.nkn.org:30003",
#           "http://mainnet-seed-0042.nkn.org:30003",
#           "http://mainnet-seed-0043.nkn.org:30003",
#           "http://mainnet-seed-0044.nkn.org:30003"
#         ],
#         "GenesisBlockProposer": "a0309f8280ca86687a30ca86556113a253762e40eb884fc6063cad2b1ebd7de5"
#       }

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nkn-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nkn
#   template:
#     metadata:
#       labels:
#         app: nkn
#     spec:
#       containers:
#         - name: nkn
#           image: nknorg/nkn
#           command: ["/bin/sh"]
#           args: ["-c", "nkn --config /nkn/custom/config.json"]
#           ports:
#             - containerPort: 30001
#               protocol: TCP
#             - containerPort: 30002
#               protocol: TCP
#             - containerPort: 30003
#               protocol: TCP
#             - containerPort: 30004
#               protocol: TCP
#           volumeMounts:
#             - name: config-volume-nkn
#               mountPath: /nkn/custom/config.json
#               subPath: config.json
#           securityContext:
#             runAsUser: 65534 # nobody user
#             runAsGroup: 65534 # nobody group
#             allowPrivilegeEscalation: false
#           readinessProbe:
#             tcpSocket:
#               port: 30001
#             initialDelaySeconds: 30
#             periodSeconds: 10
#           livenessProbe:
#             tcpSocket:
#               port: 30001
#             initialDelaySeconds: 60
#             periodSeconds: 30
#       volumes:
#         - name: config-volume-nkn
#           configMap:
#             name: nkn-config-map
#             items:
#               - key: config.json
#                 path: config.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkn-full-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nkn-full-node
  template:
    metadata:
      labels:
        app: nkn-full-node
    spec:
      containers:
        - name: nkn-full-node
          image: nknorg/nkn:latest
          command:
            - "/bin/sh"
            - "-c"
            - "wget -O nknd https://commercial.nkn.org/downloads/nkn-commercial/linux-amd64.zip && unzip linux-amd64.zip && rm -f linux-amd64.zip && mv linux-amd64/nknd . && ./nknd --config ./config.json --no-nat --data-dir ./nkn-data --log-dir ./nkn-log"
          ports:
            - containerPort: 30001
              name: p2p
            - containerPort: 30002
              name: rpc
          volumeMounts:
            - name: nkn-data
              mountPath: /nkn/nkn-data
            - name: nkn-log
              mountPath: /nkn/nkn-log
            - name: config
              mountPath: /nkn/config.json
              subPath: config.json
      volumes:
        - name: nkn-data
          persistentVolumeClaim:
            claimName: nkn-data-pvc
        - name: nkn-log
          persistentVolumeClaim:
            claimName: nkn-log-pvc
        - name: config
          configMap:
            name: nkn-config
---
apiVersion: v1
kind: Service
metadata:
  name: nkn-full-node
spec:
  type: ClusterIP
  selector:
    app: nkn-full-node
  ports:
    - name: p2p
      port: 30001
      targetPort: p2p
    - name: rpc
      port: 30002
      targetPort: rpc
