# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   creationTimestamp: null
#   labels:
#     io.kompose.service: octa-claim0
#   name: octa-claim0
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi
# status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f nodes.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: octa
  name: octa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: octa
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f nodes.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: octa
    spec:
      containers:
      - args:
          - --http
          - --http.port=8545
          - --http.addr=0.0.0.0
          - --http.api=personal,eth,net,trace,web3,txpool,miner,admin,clique
          - --http.corsdomain='*'
          - --http.vhosts='*'
          - --ws
          - --ws.port=8546
          - --ws.addr=0.0.0.0
          - --ws.api=personal,eth,net,trace,web3,txpool,miner,admin,clique
          - --ws.origins='*'
          - --allow-insecure-unlock
          - --syncmode=full
        image: gcr.io/mineonlium/octa
        imagePullPolicy: ""
        name: octa
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 38000
        resources: {
        }
        # volumeMounts:
        # - mountPath: /home/eth/.ethereum
        #   name: octa-claim0
      restartPolicy: Always
      serviceAccountName: ""
      # volumes:
      # - name: octa-claim0
      #   persistentVolumeClaim:
      #     claimName: octa-claim0
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f nodes.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: octa
  name: octa
spec:
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  - name: "8546"
    port: 8546
    targetPort: 8546
  - name: "38000"
    port: 38000
    targetPort: 38000
  selector:
    io.kompose.service: octa
status:
  loadBalancer: {}

