# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   creationTimestamp: null
#   labels:
#     io.kompose.service: ethereum-claim0
#   name: ethereum-claim0
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi
# status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f nodes.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ethereum
  name: ethereum
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ethereum
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f nodes.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ethereum
    spec:
      containers:
      - args:
        - --syncmode=light
        - --cache=8192
        - --ws
        - --ws.addr=0.0.0.0
        - --http
        - --http.addr=0.0.0.0
        - --http.vhosts=*
        - --graphql
        - --graphql.vhosts=*
        - --metrics
        - --mainnet
        - --maxpeers=30
        - --datadir=/home/eth/.ethereum
        image: ethereum/client-go:stable
        imagePullPolicy: ""
        name: ethereum
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        resources: {
        }
        # volumeMounts:
        # - mountPath: /home/eth/.ethereum
        #   name: ethereum-claim0
      restartPolicy: Always
      serviceAccountName: ""
      # volumes:
      # - name: ethereum-claim0
      #   persistentVolumeClaim:
      #     claimName: ethereum-claim0
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f nodes.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ethereum
  name: ethereum
spec:
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  - name: "8546"
    port: 8546
    targetPort: 8546
  - name: "30303"
    port: 30303
    targetPort: 30303
  selector:
    io.kompose.service: ethereum
status:
  loadBalancer: {}

