{
 "title": "teaparty",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "go_goroutines" },
    {}
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "go_threads" }
   ]
  },
  {
   "title": "go Heap Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes_total" }
   ]
  },
  { "title": "Party Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "trades_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sell_Request_totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "sell_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Buy Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "failed_buy_request_total" }
   ]
  },
  {
   "title": "Failed Sell Request Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "failed_sell_request_total" }
   ]
  },
  {
   "title": "Completed Trades Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "completed_trades_total" }
   ]
  },
  {
   "title": "Failed Trades Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "failed_trades_total" }
   ]
  }
 ]
}